$pdf_mode = 1;
$out_dir = 'build';
$aux_dir = 'build';
$bibtex_use = 2;
$max_repeat = 5;
$interaction = 'nonstopmode';
$synctex = 1;

@default_files = ('main.tex');

$clean_ext = 'acn acr alg aux bbl bcf blg fdb_latexmk fls glg glo gls ist lof log lot out run.xml synctex.gz toc';
